name: Build for Windows

on:
  push:
    branches:
      - main
      - workflows-for-windows
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      python-version: [3.10]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: powershell
        run: |
          git --version
          python --version
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build binary
        shell: powershell
        run: |
          Remove-Item -Recurse -Force wiz-scenario-data-analyzer
          git clone https://github.com/takeharukato/wiz-scenario-data-analyzer
          cd wiz-scenario-data-analyzer
          pip install -r requirements.txt
          cd src
          pyinstaller scenario.py --onedir --onefile --clean

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: result-artifact
          path: ./wiz-scenario-data-analyzer/src/dist/scenario.exe
