name: Build for Windows

on:
  push:
    branches:
      - main
      - workflows-for-windows
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        shell: powershell
        run: |
          git --version
          python --version
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build binary
        shell: powershell
        run: |
          dir
          pip install -r requirements.txt
          cd src
          pyinstaller scenario.py --onedir --onefile --clean

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: result-artifact
          path: ./src/dist/scenario.exe
